# Generated by Django 4.2.2 on 2023-06-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_windows', models.CharField(max_length=30)),
                ('code_windows', models.CharField(max_length=30)),
                ('license_windows', models.IntegerField()),
                ('user', models.ManyToManyField(to='keys.users')),
            ],
        ),
        migrations.CreateModel(
            name='Ivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ivi', models.CharField(max_length=30)),
                ('code_ivi', models.CharField(max_length=30)),
                ('license_ivi', models.IntegerField()),
                ('user', models.ManyToManyField(to='keys.users')),
            ],
        ),
    ]
