# Generated by Django 4.2.2 on 2023-07-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivi',
            name='code_ivi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ivi',
            name='license_ivi',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='windows',
            name='code_windows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='windows',
            name='license_windows',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Antivirus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_antivirus', models.CharField(max_length=30)),
                ('code_antivirus', models.IntegerField()),
                ('license_antivirus', models.CharField(max_length=30)),
                ('user', models.ManyToManyField(to='keys.users')),
            ],
        ),
    ]
