# Generated by Django 4.2.2 on 2023-07-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_alter_ivi_code_ivi_alter_ivi_license_ivi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windows',
            name='code_windows',
            field=models.CharField(max_length=30),
        ),
    ]
