# Generated by Django 4.2.2 on 2023-07-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_alter_windows_code_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antivirus',
            name='code_antivirus',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='antivirus',
            name='license_antivirus',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ivi',
            name='code_ivi',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='ivi',
            name='license_ivi',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='windows',
            name='code_windows',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='windows',
            name='license_windows',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
